### ISSUE TITLE
Error when running ./syn_yosys.sh

### ISSUE THREAD

**Issue by Merok** [lowRISC/ibex#1440]
## Observed Behavior

Hello,
I am new to Ibex and try to experiment with it.
I have an issue when running the ./syn_yosys.sh script. 
More precisely, I have such error: 
`Executing Verilog-2005 frontend: syn_out/ibex_22_09_2021_14_37_02/generated/ibex_top_tracing.v
syn_out/ibex_22_09_2021_14_37_02/generated/ibex_top_tracing.v:99: ERROR: FATAL: Fatal error: RVFI needs to be defined globally..
Failed to synthesize RTL with Yosys`

I did define the syn_setup.sh script with the Nangate45 lib.

Do you have an idea of why I get such error ?

Thanks for your help.

## My Environment

**Operating system:**

I am working on Ubuntu 20.04.3 amd64.
**Version of the Ibex source code:**

I am using the ibex source code version ac8934459b028220ce9fd20683bb018244b59756.

**Comment by rswarbrick** [comment]
@GregAC: I think you know most about our synthesis flow?

**Comment by Merok** [comment]
Hello,
Do you have some updates for my problem ?

Thanks a lot!

**Comment by tomroberts-lowrisc** [comment]
Can you let us know what versions of yosys and sv2v you are using? The script works locally for me using yosys v0.9 and sv2v v0.0.5-21-g6d907e0

**Comment by Merok** [comment]
Here are the versions I use:

* Yosys 0.9+4081 (git sha1 UNKNOWN, gcc 8.4.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os)
* sv2v v0.0.8-42-g814f965

I tried on another machine on Rocky Linux 8.4. I have the same error.
Here are my steps:
* git clone https://github.com/lowRISC/ibex.
* I installed the requirements in https://github.com/lowRISC/ibex/tree/master/syn.
* I downloaded the nangate45.lib (https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/tree/master/flow/platforms/nangate45/lib)
* I uncommented and modified the two last lines of the syn_setup.sh file such as:
```
export LR_SYNTH_CELL_LIBRARY_PATH=/test/x/Nangate45/NangateOpenCellLibrary_typical.lib
export LR_SYNTH_CELL_LIBRARY_NAME=nangate
```
* I go to the the syn directory and run syn_yosys.sh

here is the full output:

```
******  o p e n   t o   t h e   c o r e  *******

       +---------------------------------+
       |  _   _   ___   ___  _   _  ___  |
       | | | | | / _ \ / __|| | | |/ __| |
       | | |_| || (_) |\__ \| |_| |\__ \ |
       |  \__, | \___/ |___/ \__, ||___/ |
       |   __/ |              __/ |      |
       |  |___/              |___/       |
       +---------------------------------+

=================== Flow Vars ===================
Path to cell library: /XX/Nangate45/NangateOpenCellLibrary_typical.lib
top module: ibex_top (default)
Output directory for synthesis: syn_out/ibex_27_09_2021_16_54_01
Pre-mapping netlist out: ./syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top.pre_map.v (default)
netlist out: ./syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top_netlist.v (default)
Synth config file: ibex_top_lr_synth_conf.tcl (default)
Report output directory: ./syn_out/ibex_27_09_2021_16_54_01/reports (default)
flatten: Enabled
timing run: Enabled
Enable branch target ALU in Ibex: Disabled
Enable writeback stage in Ibex: Disabled
Bitmanip extenion setting for Ibex (see ibex_pkg::rv32b_e for permitted values. Enum names are not supported in Yosys.): 0 (default)
Multiplier extension setting for Ibex (see ibex_pkg::rv32m_e for permitted values. Enum names are not supported in Yosys.): 2 (default)
Register file implementation selection for Ibex (see ibex_pkg::regfile_e for permitted values. Enum names are not supported in Yosys.): 2 (default)
Name of cell library: nangate
Input SDC file: ibex_top.nangate.sdc (default)
Input SDC file for ABC: ibex_top_abc.nangate.sdc (default)
Output SDC file: ./syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top.nangate.out.sdc (default)
STA netlist out: ./syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top_netlist.sta.v (default)
STA paths reported per group: 1000 (default)
STA paths reported in overall report: 1000 (default)
clock period: 4000.0 ps
=================================================

 /----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |                                                                            |
 |  Copyright (C) 2012 - 2020  Claire Wolf <claire@symbioticeda.com>          |
 |                                                                            |
 |  Permission to use, copy, modify, and/or distribute this software for any  |
 |  purpose with or without fee is hereby granted, provided that the above    |
 |  copyright notice and this permission notice appear in all copies.         |
 |                                                                            |
 |  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES  |
 |  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF          |
 |  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR   |
 |  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    |
 |  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN     |
 |  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF   |
 |  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.            |
 |                                                                            |
 \----------------------------------------------------------------------------/

 Yosys 0.9+4081 (git sha1 UNKNOWN, gcc 8.4.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os)

1. Executing Liberty frontend.
Imported 135 cell types from liberty file.

2. Executing Verilog-2005 frontend: ./rtl/prim_clock_gating.v
Parsing SystemVerilog input from `./rtl/prim_clock_gating.v' to AST representation.
Generating RTLIL representation for module `\prim_clock_gating'.
Successfully finished Verilog frontend.

3. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_alu.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_alu.v' to AST representation.
Generating RTLIL representation for module `\ibex_alu'.
Successfully finished Verilog frontend.

4. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_branch_predict.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_branch_predict.v' to AST representation.
Generating RTLIL representation for module `\ibex_branch_predict'.
Successfully finished Verilog frontend.

5. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_compressed_decoder.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_compressed_decoder.v' to AST representation.
Generating RTLIL representation for module `\ibex_compressed_decoder'.
Successfully finished Verilog frontend.

6. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_controller.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_controller.v' to AST representation.
Generating RTLIL representation for module `\ibex_controller'.
Successfully finished Verilog frontend.

7. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_core.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_core.v' to AST representation.
Generating RTLIL representation for module `\ibex_core'.
Successfully finished Verilog frontend.

8. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_counter.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_counter.v' to AST representation.
Generating RTLIL representation for module `\ibex_counter'.
Successfully finished Verilog frontend.

9. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_cs_registers.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_cs_registers.v' to AST representation.
Generating RTLIL representation for module `\ibex_cs_registers'.
Warning: Replacing memory \pmp_addr_rdata with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_cs_registers.v:852
Warning: Replacing memory \mhpmevent with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_cs_registers.v:897
Successfully finished Verilog frontend.

10. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_csr.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_csr.v' to AST representation.
Generating RTLIL representation for module `\ibex_csr'.
Successfully finished Verilog frontend.

11. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_decoder.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_decoder.v' to AST representation.
Generating RTLIL representation for module `\ibex_decoder'.
Successfully finished Verilog frontend.

12. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_dummy_instr.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_dummy_instr.v' to AST representation.
Generating RTLIL representation for module `\ibex_dummy_instr'.
Successfully finished Verilog frontend.

13. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_ex_block.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_ex_block.v' to AST representation.
Generating RTLIL representation for module `\ibex_ex_block'.
Successfully finished Verilog frontend.

14. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_fetch_fifo.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_fetch_fifo.v' to AST representation.
Generating RTLIL representation for module `\ibex_fetch_fifo'.
Successfully finished Verilog frontend.

15. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_icache.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_icache.v' to AST representation.
Generating RTLIL representation for module `\ibex_icache'.
Warning: Replacing memory \fill_data_q with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_icache.v:630
Warning: Replacing memory \fill_way_q with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_icache.v:608
Warning: Replacing memory \fill_addr_q with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_icache.v:596
Successfully finished Verilog frontend.

16. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_id_stage.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_id_stage.v' to AST representation.
Generating RTLIL representation for module `\ibex_id_stage'.
Successfully finished Verilog frontend.

17. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_if_stage.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_if_stage.v' to AST representation.
Generating RTLIL representation for module `\ibex_if_stage'.
Successfully finished Verilog frontend.

18. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_load_store_unit.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_load_store_unit.v' to AST representation.
Generating RTLIL representation for module `\ibex_load_store_unit'.
Successfully finished Verilog frontend.

19. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_lockstep.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_lockstep.v' to AST representation.
Generating RTLIL representation for module `\ibex_lockstep'.
Warning: Replacing memory \shadow_data_rdata_q with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_lockstep.v:227
Warning: Replacing memory \shadow_tag_rdata_q with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_lockstep.v:226
Successfully finished Verilog frontend.

20. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_multdiv_fast.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_multdiv_fast.v' to AST representation.
Generating RTLIL representation for module `\ibex_multdiv_fast'.
Successfully finished Verilog frontend.

21. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_multdiv_slow.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_multdiv_slow.v' to AST representation.
Generating RTLIL representation for module `\ibex_multdiv_slow'.
Successfully finished Verilog frontend.

22. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_pmp.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_pmp.v' to AST representation.
Generating RTLIL representation for module `\ibex_pmp'.
Successfully finished Verilog frontend.

23. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_prefetch_buffer.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_prefetch_buffer.v' to AST representation.
Generating RTLIL representation for module `\ibex_prefetch_buffer'.
Successfully finished Verilog frontend.

24. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_register_file_latch.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_register_file_latch.v' to AST representation.
Generating RTLIL representation for module `\ibex_register_file_latch'.
Warning: Replacing memory \mem with list of registers. See syn_out/ibex_27_09_2021_16_54_01/generated/ibex_register_file_latch.v:113, syn_out/ibex_27_09_2021_16_54_01/generated/ibex_register_file_latch.v:87
Successfully finished Verilog frontend.

25. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top.v
Parsing SystemVerilog input from `syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top.v' to AST representation.
Generating RTLIL representation for module `\ibex_top'.
Successfully finished Verilog frontend.

26. Executing Verilog-2005 frontend: syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top_tracing.v
syn_out/ibex_27_09_2021_16_54_01/generated/ibex_top_tracing.v:99: ERROR: FATAL: Fatal error: RVFI needs to be defined globally..
Failed to synthesize RTL with Yosys
```

**Comment by Merok** [comment]
Hi, 
Any help on this error would be greatly appreciated.

Thanks.

**Comment by imphil** [comment]
Please try using the exact same versions of yosys and sv2v as @tomroberts-lowrisc mentioned above; the syn_yosys.sh scripting is highly fragile (and unsupported), so if you'd like to use other versions you'll probably need to do some digging yourself.

**Comment by GregAC** [comment]
I can also run `syn_yosys.sh` without issue. I'm using an older version of sv2v and yosys (sv2v v0.0.5-18-ga170536 and Yosys 0.9+1706 (git sha1 968956ba, clang 6.0.0-1ubuntu2 -fPIC -Os). It looks like either the newer sv2v is translating things a bit differently and yosys doesn't like it or sv2v is emitting some slightly broken verilog that previously yosys didn't care about but now does.

**Comment by Merok** [comment]
Hi,

Thanks for the help.
Indeed, the ./syn_yosis.sh script works now with sv2v v0.0.5-18-ga170536.

**Comment by zachjs** [comment]
Please try out https://github.com/lowRISC/ibex/pull/1449, which should make the flow work with both older and newer versions of sv2v.
